export const skills = {
  frontend: [
    "React",
    "TypeScript",
    "Next.js",
    "Redux Toolkit",
    "React Query",
    "Zustand",
    "React Router",
    "Vite",
    "Storybook",
    "Formik",
    "React Hook Form",
    "Styled Components",
    "MUI",
    "Ant Design",
    "GraphQL",
    "Chart.js",
  ],
  backend: [
    "Node.js",
    "REST API",
    "Redis",
    "Git",
    "GitHub",
    "Docker",
    "ESLint",
    "Prettier",
    "Husky",
  ],
  practices: [
    "SSR",
    "Hydration",
    "SEO",
    "Performance Optimization",
    "SOLID",
    "Component Architecture",
  ],
};
